server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_utility_payment_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    
info:
  app:
    name: ${spring.application.name}
