spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_user_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: javatodev-internet-banking
      clientId: internet-banking-core-client
      client-secret: ob8aF28f9OD8lIdaKXiVec7JKZoFi778
  feign:
    client:
      core-banking: core-banking-service
