eureka:
  client:
    service-url:
      defaultZone: http://eureka-in:9001/eureka/,http://eureka-jp:9002/eureka/,http://eureka-us:9003/eureka/
spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 8001
